language: php

sudo: false

php:
  - 8.0
  - 8.1
  - 8.2

env: TMPDIR=/tmp USE_XDEBUG=false

services:
- memcached

branches:
  only:
    master

before_install:
  - travis_retry composer self-update

install:
  - phpenv rehash
  - travis_retry composer install --no-interaction --prefer-source

script:
 - cd tests/
 - php runalltests.php

