language: php
php:
  - "5.2.11"
  - "5.3"
  - "5.4"

env: TMPDIR=/tmp

before_install:
 - phpenv rehash
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

before_script:
 - composer require siad007/zf1:1.12.*

script:
 - cd tests/
 - php runalltests.php
