language: php
php:
  - "5.2"
  - "5.3"
  - "5.4"

env: TMPDIR=/tmp

before_install:
 - phpenv rehash
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

before_script:
 - composer require zendframework/zendframework1:1.12.*@dev
 - composer install

script:
 - cd vendor/
 - ls -la
 - cd ../
 - cd tests/
 - php runalltests.php
