language: php
php:
  - "5.2"
  - "5.3"
  - "5.4"

env: TMPDIR=/tmp

before_install:
 - phpenv rehash
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

before_script:
 - if [[ "$TRAVIS_PHP_VERSION" == "5.2.17" ]]; then pecl install phar; fi
 - composer require zendframework/zendframework1:1.12.*@dev
 - composer install

script:
 - cp -rf vendor/zendframework/zendframework1/library/Zend library/Zend
 - cp -rf vendor/zendframework/zendframework1/tests/Zend tests/Zend
 - cd tests/
 - php runalltests.php
